--- 
- name: Limpa iDocuments 
  hosts: all
  gather_facts: false
  tasks:
   - name: Chama o batman pra apagar
   - win_domain_membership:
       dns_domain_name: DOMINIO.CDB
       domain_admin_user: adjsilva@DOMINIO
       domain_admin_password: dnjx56(jeh)	
       state: domain
       register: domain_state
       win_shell: "remove-item -path c:\\Users\\Admin*\\iDocuments\\* -Force"
