- name:  Windows Update
  hosts: dhcp 
  strategy: free
  tasks:
    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates']
      register: result

    # output results
    - debug: var=result
    
    # reboot only if required
    - win_reboot:
      when: result.reboot_required
      notify:
      - Running Windows Update
      when: result.found_update_count > 0
